#!/bin/bash

echo "Initializing..."
# Set the name of virtual environment
venv_name="env"

echo "Creating virtual environment..."
# Create a virtual environment
if [ -d "$venv_name" ]; then
    echo "Virtual environment already exists."
else
    python3 -m venv $venv_name
fi

echo "Activating virtual environment..."
# Activate the virtual environment
source $venv_name/bin/activate

echo "Installing dependencies..."
# Install required dependencies (add here as needed)
dependencies=("multipledispatch" "tk" "python-dotenv")

# we are doing a pip upgrade just in case
pip install --upgrade pip

for dependency in "${dependencies[@]}"; do
    if pip show "$dependency" > /dev/null 2>&1; then
        echo "$dependency is installed."
    else
        echo "Installing $dependency..."
        pip install "$dependency"
    fi
done

# clean up a bit
clear

echo "Starting server..."

# Run python script
python server.py

# Deactivate the virtual environment when done
deactivate
